language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
env:
before_install:
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt541
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 qt54tools
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      && sudo apt-get install libssl-dev
      ;
    else
         brew update
      && brew install qt5
      && brew install qt5-qmake
      && chmod -R 755 /usr/local/opt/qt5/*
      ;
    fi

- wget http://www.cmake.org/files/v3.3/cmake-3.3.2.tar.gz
- tar -xvf cmake-3.3.2.tar.gz
- cd cmake-3.3.2
- ./configure && make && sudo make install
- cd ../
- rm -rf cmake-3.3.2
- rm cmake-3.3.2.tar.gz

script:
  - /opt/qt54/bin/qt54-env.sh 
  - git submodule update --init --recursive 
  - cd build
  - sh ./rebuild.sh /dev/null /dev/null
after_success:
  - sh ./clean.sh
services:

notifications:
  recipients:
    - atopilski@fastogt.com
  email:
    on_success: change
    on_failure: change
